package com.codingcompetition.statefarm;

public enum Category {

	LEISURE, NAME, AMENITY, CUISINE, SHOP, WHEELCHAIR, HIGHWAY, PLACE, POPULATION, POWER, BUILDING, BEAUTY,
	NAMESTARTSWITH, NAMEENDSWITH;
}
